/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import efectos.MaterialColor;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class FormDepRet extends javax.swing.JFrame {

    /**
     * Creates new form FormAcces
     */
    public FormDepRet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSTexFieldMD1 = new LIB.FSTexFieldMD();
        fadeEffect1 = new LIB.FadeEffect();
        materialColor1 = new efectos.MaterialColor();
        jSeparator2 = new javax.swing.JSeparator();
        groupViewDepReg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNameUser = new javax.swing.JLabel();
        lblSaldoUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConfirmOperation = new javax.swing.JButton();
        btnCancelOperation = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorResta = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblMessageSuccessful = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGroupDep = new javax.swing.JRadioButton();
        btnGroupRet = new javax.swing.JRadioButton();

        fSTexFieldMD1.setText("fSTexFieldMD1");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblNameUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameUser.setText("Jonnathan Gallegos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        lblSaldoUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaldoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoUser.setText("$ 100 ");
        getContentPane().add(lblSaldoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 75, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Valor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 83, 40));

        btnConfirmOperation.setText("Confirm");
        getContentPane().add(btnConfirmOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 136, 43));

        btnCancelOperation.setText("Salir");
        btnCancelOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOperationActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 136, 43));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 204));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 230, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Saldo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 75, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Opción:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 83, 40));

        txtValorResta.setBackground(new java.awt.Color(204, 255, 255));
        txtValorResta.setBorder(null);
        getContentPane().add(txtValorResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 204));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, 20));

        lblMessageSuccessful.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMessageSuccessful.setForeground(new java.awt.Color(0, 0, 255));
        lblMessageSuccessful.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessageSuccessful.setText("Retiro realizado con éxito");
        getContentPane().add(lblMessageSuccessful, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 270, 330, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 350, 30));

        groupViewDepReg.add(btnGroupDep);
        btnGroupDep.setText("Depocito");
        getContentPane().add(btnGroupDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        groupViewDepReg.add(btnGroupRet);
        btnGroupRet.setText("Retiro");
        getContentPane().add(btnGroupRet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelOperationActionPerformed

    public JButton getBtnCancelOperation() {
        return btnCancelOperation;
    }

    public void setBtnCancelOperation(JButton btnCancelOperation) {
        this.btnCancelOperation = btnCancelOperation;
    }

    public JButton getBtnConfirmOperation() {
        return btnConfirmOperation;
    }

    public void setBtnConfirmOperation(JButton btnConfirmOperation) {
        this.btnConfirmOperation = btnConfirmOperation;
    }

    public JLabel getLblMessageSuccessful() {
        return lblMessageSuccessful;
    }

    public void setLblMessageSuccessful(JLabel lblMessageSuccessful) {
        this.lblMessageSuccessful = lblMessageSuccessful;
    }

    public JLabel getLblNameUser() {
        return lblNameUser;
    }

    public void setLblNameUser(JLabel lblNameUser) {
        this.lblNameUser = lblNameUser;
    }

    public JLabel getLblSaldoUser() {
        return lblSaldoUser;
    }

    public void setLblSaldoUser(JLabel lblSaldoUser) {
        this.lblSaldoUser = lblSaldoUser;
    }

    public MaterialColor getMaterialColor1() {
        return materialColor1;
    }

    public void setMaterialColor1(MaterialColor materialColor1) {
        this.materialColor1 = materialColor1;
    }

    public JTextField getTxtValorResta() {
        return txtValorResta;
    }

    public void setTxtValorResta(JTextField txtValorResta) {
        this.txtValorResta = txtValorResta;
    }

    public JRadioButton getBtnGroupDep() {
        return btnGroupDep;
    }

    public void setBtnGroupDep(JRadioButton btnGroupDep) {
        this.btnGroupDep = btnGroupDep;
    }

    public JRadioButton getBtnGroupRet() {
        return btnGroupRet;
    }

    public void setBtnGroupRet(JRadioButton btnGroupRet) {
        this.btnGroupRet = btnGroupRet;
    }

    public ButtonGroup getGroupViewDepReg() {
        return groupViewDepReg;
    }

    public void setGroupViewDepReg(ButtonGroup groupViewDepReg) {
        this.groupViewDepReg = groupViewDepReg;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOperation;
    private javax.swing.JButton btnConfirmOperation;
    private javax.swing.JRadioButton btnGroupDep;
    private javax.swing.JRadioButton btnGroupRet;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private LIB.FadeEffect fadeEffect1;
    private javax.swing.ButtonGroup groupViewDepReg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblMessageSuccessful;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblSaldoUser;
    private efectos.MaterialColor materialColor1;
    private javax.swing.JTextField txtValorResta;
    // End of variables declaration//GEN-END:variables
}
